#! /bin/sh
nitrogen --restore
pkill polybar
xrandr --output HDMI-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output eDP-1-1 --mode 1920x1080 --pos 2560x0 --rotate normal
polybar &
sxhkd -c ~/.config/sxhkd/sxhkdrc &

bspc monitor HDMI-0 -d   󰗃  
bspc monitor eDP-1-1 -d 󰙯   

# Rosé pine 
bspc config focused_border_color "#eb6f92"
bspc config normal_border_color "#ebbcba"

bspc config border_width         2
bspc config window_gap          12

bspc config -m eDP-1-1 top_padding 0
bspc config -m HDMI-0 top_padding 54
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
bspc rule -a discord desktop='^6'
bspc rule -a Alacritty state=floating

